apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hub-uploads-pvc
  namespace: hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hub-wpp-pvc
  namespace: hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
