apiVersion: v1
kind: Service
metadata:
  name: hub-backend
  namespace: hub
spec:
  selector:
    app: hub-backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000        # Puerto interno del cluster
      targetPort: 4000  # Puerto del contenedor
      nodePort: 30400   # Puerto expuesto en la VM (Nginx apunta aquí)
